// English wording for the community survey. Written plain on purpose -
// aim for about a 5th-grade reading level when editing. Other languages
// copy this file's shape exactly (see languages.js).
const en = {
  ui: {
    language: 'Language',
    quickExit: 'Quick Exit',
    quickExitHint: 'Leave this page fast. Your answers will be erased.',
    quickExitKeyHint: 'You can also press Esc.',
    quickExitExplain: 'Need to leave fast? Tap Quick Exit at the top. It erases your answers and opens a weather page.',
    backHome: 'Back to Feed Sioux Falls',
    safetyTip:
      'Safety tip: Quick Exit leaves this page right away. Your web browser may still remember that you were here. If that matters, clear your browser history after, or use a private window.',

    title: 'Sioux Falls Community Survey',
    intro: [
      'Feed Sioux Falls has been talking with Sioux Falls City Council members. We want a true picture of the people in our city who are unhoused or in need: who you are, what helps, and what isn’t working.',
      'A one-day count misses too many people. You can help change that.',
      'Every question is optional. You do not have to give your name. Answer only what you are comfortable with.',
    ],
    time: 'About 3 minutes',
    start: 'Start',
    resumeTitle: 'Answers were saved on this phone',
    resumeBody: 'Someone started this survey earlier. Do you want to keep going, or start fresh?',
    resume: 'Keep going',
    startOver: 'Start fresh',
    clearAnswers: 'Erase my answers',
    clearConfirm: 'Erase all your answers and start over?',
    savedNote: 'Your answers save on this phone as you go, in case you lose signal. They are erased when you send the survey.',

    stepOf: (n, total) => `Step ${n} of ${total}`,
    next: 'Next',
    skip: 'Skip',
    back: 'Back',
    submit: 'Send my survey',
    submitting: 'Sending…',
    submitError: 'We could not send your survey. Check your signal and try again. Your answers are still here.',

    chooseOne: 'Choose one',
    chooseAll: 'Choose all that apply',
    preferNot: 'Prefer not to say',
    typeHere: 'Type here (optional)',
    readAloud: 'Read aloud',
    stopReading: 'Stop reading',

    contactTitle: 'Would you like someone to contact you?',
    contactHint: 'Only if you want. This is kept apart from your answers above.',
    contactYes: 'Yes, contact me',
    contactNo: 'No thanks',
    contactName: 'Your name or a nickname (optional)',
    contactPhone: 'Phone number',
    contactEmail: 'Email',
    contactNeedOne: 'Please add a phone number or email so we can reach you.',
    contactBestTime: 'Best time to reach you (optional)',
    contactSafe: 'Is it safe to leave you a message?',
    contactSafeYes: 'Yes, it’s safe',
    contactSafeNo: 'No, do not leave a message',
    contactTearOff: 'Tear this part off. It is kept apart from your answers.',

    whoSeesTitle: 'Who sees this',
    whoSees: [
      'Only Feed Sioux Falls will see your answers. We share totals with Sioux Falls City Council (like “40 people said they have no photo ID”), never anyone’s own answers.',
      'We use this to look for ways to change or add services that help people get housed, find work, and get what they need to live in Sioux Falls.',
      'If you left contact info, only Feed Sioux Falls will use it to reach you. It is kept apart from your answers.',
      'We do not ask your name, and we do not save your location or internet address.',
    ],

    thanksTitle: 'Thank you',
    thanksBody: 'Your survey was sent. Your answers have been erased from this phone.',
    thanksContact: 'Someone from Feed Sioux Falls will reach out.',
    startAnother: 'Start a new survey',

    shareTitle: 'Know someone who should fill this out?',
    shareButton: 'Share this survey',
    shareMessage: 'Feed Sioux Falls wants to hear from people in Sioux Falls who are unhoused or in need. It takes about 3 minutes and you can stay anonymous:',
    shareText: 'Text',
    shareEmail: 'Email',
    shareEmailSubject: 'Sioux Falls Community Survey',
    copyLink: 'Copy link',
    copied: 'Link copied',
    showQr: 'Show QR code',
    hideQr: 'Hide QR code',
    qrHint: 'Hold this up so someone can scan it with their phone camera.',
    printPaper: 'Print a paper version',

    // Only shown to logged-in volunteers/admins.
    sourceTitle: 'How is this being filled out?',
    sourceVolunteer: 'I’m helping someone in person',
    sourcePaper: 'I’m typing in a paper survey',
  },

  sections: {
    start: 'Getting started',
    where: 'Where you are',
    housing: 'Housing',
    about: 'About you',
    applies: 'Check any that apply',
    work: 'Work and basics',
    services: 'Services',
    voice: 'Your voice',
    contact: 'Staying in touch',
  },

  q: {
    repeat: {
      label: 'Have you filled out this survey before?',
      hint: 'This helps us count people over time without names.',
      options: {
        first_time: 'No, this is my first time',
        yes_changed: 'Yes, but things have changed',
        yes_same: 'Yes, and things are about the same',
      },
    },
    slept_last_night: {
      label: 'Where did you sleep last night?',
      options: {
        shelter: 'A shelter',
        outside: 'Outside (street, park, camp)',
        vehicle: 'A car, van, or RV',
        couch: 'With friends or family (couch-surfing)',
        motel: 'A motel or hotel',
        own_place: 'My own place',
        hospital_jail_treatment: 'Hospital, jail, or treatment',
        other: 'Somewhere else',
      },
    },
    area: {
      label: 'What part of town do you spend the most time in?',
      options: {
        downtown: 'Downtown',
        northwest: 'Northwest',
        northeast: 'Northeast',
        southwest: 'Southwest',
        southeast: 'Southeast',
        outside_city: 'Outside Sioux Falls',
        not_sure: 'Not sure',
      },
    },
    housing_length: {
      label: 'How long have you been without a steady place to live?',
      options: {
        housed: 'I have a steady place now',
        under_1_month: 'Less than 1 month',
        '1_6_months': '1 to 6 months',
        '6_12_months': '6 months to 1 year',
        '1_3_years': '1 to 3 years',
        over_3_years: 'More than 3 years',
      },
    },
    first_time_homeless: {
      label: 'Is this the first time you have been without housing?',
      options: { yes: 'Yes', no: 'No' },
    },
    time_in_sf: {
      label: 'How long have you been in Sioux Falls?',
      options: {
        under_1_month: 'Less than 1 month',
        '1_12_months': '1 month to 1 year',
        '1_5_years': '1 to 5 years',
        over_5_years: 'More than 5 years',
        whole_life: 'My whole life',
      },
    },
    causes: {
      label: 'What led to losing your housing?',
      options: {
        job_loss: 'Lost a job or hours',
        rent_increase: 'Rent went up',
        eviction: 'Eviction',
        domestic_violence: 'Leaving abuse or violence',
        health: 'Health problems',
        family: 'Family problems or breakup',
        left_jail: 'Leaving jail or prison',
        left_foster_care: 'Leaving foster care',
        other: 'Something else',
      },
    },
    age: {
      label: 'How old are you?',
      options: {
        under_18: 'Under 18',
        '18_24': '18 to 24',
        '25_34': '25 to 34',
        '35_44': '35 to 44',
        '45_54': '45 to 54',
        '55_64': '55 to 64',
        '65_plus': '65 or older',
      },
    },
    gender: {
      label: 'What is your gender?',
      options: {
        woman: 'Woman',
        man: 'Man',
        nonbinary: 'Nonbinary',
        transgender: 'Transgender',
        two_spirit: 'Two-Spirit',
        other: 'Something else',
      },
    },
    race: {
      label: 'What is your race or ethnicity?',
      options: {
        american_indian: 'American Indian or Alaska Native',
        asian: 'Asian',
        black: 'Black or African American',
        hispanic: 'Hispanic or Latino',
        middle_eastern: 'Middle Eastern or North African',
        pacific_islander: 'Native Hawaiian or Pacific Islander',
        white: 'White',
        other: 'Something else',
      },
    },
    with_you: {
      label: 'Who is with you?',
      hint: 'Pets count too. Many shelters don’t take pets.',
      options: {
        alone: 'Just me',
        partner: 'A partner or spouse',
        kids: 'Kids',
        other_family: 'Other family',
        friends: 'Friends',
        pets: 'Pets',
      },
    },
    kids_count: {
      label: 'How many kids are with you?',
      options: { 1: '1', 2: '2', 3: '3', 4: '4', '5_plus': '5 or more' },
    },
    applies: {
      label: 'Do any of these apply to you?',
      options: {
        veteran: 'Veteran',
        dv_survivor: 'Survivor of domestic violence',
        disability: 'Have a disability',
        physical_health: 'Physical health needs',
        mental_health: 'Mental health needs',
        substance_use: 'Alcohol or drug use',
        pregnant: 'Pregnant',
        lgbtq: 'LGBTQ+',
        foster_youth: 'Was in foster care',
        recently_released: 'Recently released from jail or prison',
      },
    },
    work: {
      label: 'Are you working?',
      options: {
        full_time: 'Full time',
        part_time: 'Part time',
        day_labor: 'Day labor or odd jobs',
        looking: 'Looking for work',
        unable: 'Not able to work',
        not_looking: 'Not working right now',
      },
    },
    income: {
      label: 'Where does your money come from?',
      options: {
        job: 'A job',
        ssi_ssdi: 'SSI or SSDI (disability)',
        va: 'VA benefits',
        snap: 'SNAP (food stamps)',
        tanf: 'TANF (cash help)',
        unemployment: 'Unemployment',
        family_help: 'Help from family or friends',
        odd_jobs: 'Odd jobs, recycling, or asking for help',
        none: 'No money coming in',
        other: 'Something else',
      },
    },
    photo_id: {
      label: 'Do you have a photo ID?',
      options: { yes: 'Yes', no: 'No', lost_stolen: 'I had one, but it was lost or stolen' },
    },
    phone: {
      label: 'Do you have a phone?',
      options: { yes_works: 'Yes, and it works', yes_no_service: 'Yes, but no service or minutes', no: 'No' },
    },
    services_used: {
      label: 'What services do you use?',
      options: {
        food_pantry: 'Food pantry',
        meals: 'Free meals',
        shelter: 'Shelter',
        day_center: 'Day center',
        health_clinic: 'Health clinic',
        mental_health: 'Mental health care',
        addiction_treatment: 'Drug or alcohol treatment',
        job_help: 'Job help',
        housing_help: 'Housing help',
        id_help: 'Help getting an ID',
        showers_laundry: 'Showers or laundry',
        transportation: 'Bus passes or rides',
        none: 'None',
      },
    },
    services_barriers: {
      label: 'What makes services hard to use?',
      options: {
        hours: 'Hours don’t work for me',
        transportation: 'Hard to get there',
        rules: 'The rules',
        no_pets: 'They don’t allow pets',
        waitlist: 'Waitlists',
        no_id: 'I need an ID',
        full: 'They are full',
        feel_unsafe: 'I don’t feel safe there',
        dont_know_where: 'I don’t know where to go',
        no_phone: 'I need a phone',
        other: 'Something else',
      },
    },
    services_missing: {
      label: 'What help is missing in Sioux Falls?',
    },
    council_message: {
      label: 'What do you want City Council to know?',
    },
  },

  // Shown when someone picks a language we don't have a translation for yet.
  placeholder: {
    title: 'Help us translate this survey',
    body: [
      'We don’t have this survey in your language yet. We would love a neighbor’s help translating it.',
      'You can fill out the survey in English or Spanish now. If you can help translate, send us a note below.',
    ],
    useEnglish: 'Continue in English',
    useSpanish: 'Continuar en español',
    helpTitle: 'I can help translate',
    helpName: 'Your name (optional)',
    helpContact: 'Phone or email',
    helpSend: 'Send',
    helpSent: 'Thank you! We’ll be in touch.',
    helpNeedContact: 'Please add a phone or email so we can reach you.',
    helpMessage: (languageName) => `I can help translate the community survey into ${languageName}.`,
  },
};

export default en;
