// Spanish wording for the community survey.
// DRAFT - needs review by a native Spanish speaker before launch,
// ideally someone from the community the survey is for.
const es = {
  ui: {
    language: 'Idioma',
    quickExit: 'Salida rápida',
    quickExitHint: 'Salga de esta página rápido. Sus respuestas se borrarán.',
    quickExitKeyHint: 'También puede presionar Esc.',
    quickExitExplain: '¿Necesita salir rápido? Toque Salida rápida arriba. Borra sus respuestas y abre una página del clima.',
    backHome: 'Volver a Feed Sioux Falls',
    backHomeGuest: 'Volver al inicio e iniciar sesión',
    safetyTip:
      'Consejo de seguridad: Salida rápida cierra esta página de inmediato. Su navegador todavía puede recordar que estuvo aquí. Si eso le preocupa, borre el historial del navegador después, o use una ventana privada.',

    title: 'Encuesta comunitaria de Sioux Falls',
    intro: [
      'Feed Sioux Falls ha estado hablando con miembros del Concejo Municipal de Sioux Falls. Queremos conocer de verdad a las personas de nuestra ciudad que no tienen vivienda o que necesitan ayuda: quiénes son, qué les ayuda y qué no está funcionando.',
      'Un conteo de un solo día deja fuera a muchas personas. Usted puede ayudar a cambiar eso.',
      'Todas las preguntas son opcionales. No tiene que dar su nombre. Conteste solo lo que le haga sentir cómodo.',
    ],
    time: 'Unos 3 minutos',
    start: 'Empezar',
    resumeTitle: 'Hay respuestas guardadas en este teléfono',
    resumeBody: 'Alguien empezó esta encuesta antes. ¿Quiere continuar o empezar de nuevo?',
    resume: 'Continuar',
    startOver: 'Empezar de nuevo',
    clearAnswers: 'Borrar mis respuestas',
    clearConfirm: '¿Borrar todas sus respuestas y empezar de nuevo?',
    savedNote: 'Sus respuestas se guardan en este teléfono mientras avanza, por si pierde la señal. Se borran cuando envía la encuesta.',

    stepOf: (n, total) => `Paso ${n} de ${total}`,
    next: 'Siguiente',
    skip: 'Saltar',
    back: 'Atrás',
    submit: 'Enviar mi encuesta',
    submitting: 'Enviando…',
    submitError: 'No pudimos enviar su encuesta. Revise su señal e intente otra vez. Sus respuestas siguen aquí.',

    chooseOne: 'Elija una',
    chooseAll: 'Elija todas las que apliquen',
    preferNot: 'Prefiero no decir',
    typeHere: 'Escriba aquí (opcional)',
    readAloud: 'Leer en voz alta',
    stopReading: 'Dejar de leer',

    contactTitle: '¿Quiere que alguien se comunique con usted?',
    contactHint: 'Solo si usted quiere. Esto se guarda aparte de sus respuestas.',
    contactYes: 'Sí, comuníquense conmigo',
    contactNo: 'No, gracias',
    contactName: 'Su nombre o apodo (opcional)',
    contactPhone: 'Número de teléfono',
    contactEmail: 'Correo electrónico',
    contactNeedOne: 'Por favor agregue un teléfono o correo para poder comunicarnos.',
    contactBestTime: 'Mejor hora para comunicarnos (opcional)',
    contactSafe: '¿Es seguro dejarle un mensaje?',
    contactSafeYes: 'Sí, es seguro',
    contactSafeNo: 'No, no dejen mensaje',
    contactTearOff: 'Corte esta parte. Se guarda aparte de sus respuestas.',

    whoSeesTitle: 'Quién ve esto',
    whoSees: [
      'Solo Feed Sioux Falls verá sus respuestas. Compartimos totales con el Concejo Municipal de Sioux Falls (por ejemplo, “40 personas dijeron que no tienen identificación con foto”), nunca las respuestas de una persona.',
      'Usamos esto para buscar maneras de cambiar o agregar servicios que ayuden a las personas a conseguir vivienda, encontrar trabajo y tener lo que necesitan para vivir en Sioux Falls.',
      'Si dejó sus datos de contacto, solo Feed Sioux Falls los usará para comunicarse con usted. Se guardan aparte de sus respuestas.',
      'No pedimos su nombre, y no guardamos su ubicación ni su dirección de internet.',
    ],

    thanksTitle: 'Gracias',
    thanksBody: 'Su encuesta fue enviada. Sus respuestas se borraron de este teléfono.',
    thanksContact: 'Alguien de Feed Sioux Falls se comunicará con usted.',
    startAnother: 'Empezar una encuesta nueva',

    shareTitle: '¿Conoce a alguien que debería llenar esto?',
    shareButton: 'Compartir esta encuesta',
    shareMessage: 'Feed Sioux Falls quiere escuchar a las personas de Sioux Falls que no tienen vivienda o que necesitan ayuda. Toma unos 3 minutos y puede ser anónima:',
    shareText: 'Mensaje de texto',
    shareEmail: 'Correo',
    shareEmailSubject: 'Encuesta comunitaria de Sioux Falls',
    copyLink: 'Copiar enlace',
    copied: 'Enlace copiado',
    showQr: 'Mostrar código QR',
    hideQr: 'Ocultar código QR',
    qrHint: 'Muéstrelo para que alguien lo escanee con la cámara de su teléfono.',
    printPaper: 'Imprimir una versión en papel',

    sourceTitle: '¿Cómo se está llenando esta encuesta?',
    sourceVolunteer: 'Estoy ayudando a alguien en persona',
    sourcePaper: 'Estoy pasando una encuesta en papel',
  },

  sections: {
    start: 'Para empezar',
    where: 'Dónde está',
    housing: 'Vivienda',
    about: 'Sobre usted',
    applies: 'Marque las que apliquen',
    work: 'Trabajo y lo básico',
    services: 'Servicios',
    voice: 'Su voz',
    contact: 'Mantenernos en contacto',
  },

  q: {
    repeat: {
      label: '¿Ha llenado esta encuesta antes?',
      hint: 'Esto nos ayuda a contar a las personas con el tiempo sin usar nombres.',
      options: {
        first_time: 'No, es la primera vez',
        yes_changed: 'Sí, pero las cosas han cambiado',
        yes_same: 'Sí, y las cosas están más o menos igual',
      },
    },
    slept_last_night: {
      label: '¿Dónde durmió anoche?',
      options: {
        shelter: 'En un albergue',
        outside: 'Afuera (calle, parque, campamento)',
        vehicle: 'En un carro, camioneta o casa rodante',
        couch: 'Con amigos o familia',
        motel: 'En un motel u hotel',
        own_place: 'En mi propia casa',
        hospital_jail_treatment: 'Hospital, cárcel o centro de tratamiento',
        other: 'En otro lugar',
      },
    },
    area: {
      label: '¿En qué parte de la ciudad pasa más tiempo?',
      options: {
        downtown: 'Centro',
        northwest: 'Noroeste',
        northeast: 'Noreste',
        southwest: 'Suroeste',
        southeast: 'Sureste',
        outside_city: 'Fuera de Sioux Falls',
        not_sure: 'No estoy seguro/a',
      },
    },
    housing_length: {
      label: '¿Cuánto tiempo lleva sin un lugar fijo donde vivir?',
      options: {
        housed: 'Ahora tengo un lugar fijo',
        under_1_month: 'Menos de 1 mes',
        '1_6_months': 'De 1 a 6 meses',
        '6_12_months': 'De 6 meses a 1 año',
        '1_3_years': 'De 1 a 3 años',
        over_3_years: 'Más de 3 años',
      },
    },
    first_time_homeless: {
      label: '¿Es la primera vez que está sin vivienda?',
      options: { yes: 'Sí', no: 'No' },
    },
    time_in_sf: {
      label: '¿Cuánto tiempo lleva en Sioux Falls?',
      options: {
        under_1_month: 'Menos de 1 mes',
        '1_12_months': 'De 1 mes a 1 año',
        '1_5_years': 'De 1 a 5 años',
        over_5_years: 'Más de 5 años',
        whole_life: 'Toda mi vida',
      },
    },
    causes: {
      label: '¿Qué le llevó a perder su vivienda?',
      options: {
        job_loss: 'Perdí el trabajo o horas',
        rent_increase: 'Subió la renta',
        eviction: 'Desalojo',
        domestic_violence: 'Salir de abuso o violencia',
        health: 'Problemas de salud',
        family: 'Problemas familiares o separación',
        left_jail: 'Salir de la cárcel o prisión',
        left_foster_care: 'Salir de cuidado de crianza (foster care)',
        other: 'Otra cosa',
      },
    },
    age: {
      label: '¿Cuántos años tiene?',
      options: {
        under_18: 'Menos de 18',
        '18_24': 'De 18 a 24',
        '25_34': 'De 25 a 34',
        '35_44': 'De 35 a 44',
        '45_54': 'De 45 a 54',
        '55_64': 'De 55 a 64',
        '65_plus': '65 o más',
      },
    },
    gender: {
      label: '¿Cuál es su género?',
      options: {
        woman: 'Mujer',
        man: 'Hombre',
        nonbinary: 'No binario',
        transgender: 'Transgénero',
        two_spirit: 'Dos Espíritus (Two-Spirit)',
        other: 'Otro',
      },
    },
    race: {
      label: '¿Cuál es su raza u origen étnico?',
      options: {
        american_indian: 'Indígena americano o nativo de Alaska',
        asian: 'Asiático',
        black: 'Negro o afroamericano',
        hispanic: 'Hispano o latino',
        middle_eastern: 'De Medio Oriente o del norte de África',
        pacific_islander: 'Nativo de Hawái o de las islas del Pacífico',
        white: 'Blanco',
        other: 'Otro',
      },
    },
    with_you: {
      label: '¿Quién está con usted?',
      hint: 'Las mascotas cuentan también. Muchos albergues no aceptan mascotas.',
      options: {
        alone: 'Solo yo',
        partner: 'Mi pareja o esposo/a',
        kids: 'Niños',
        other_family: 'Otros familiares',
        friends: 'Amigos',
        pets: 'Mascotas',
      },
    },
    kids_count: {
      label: '¿Cuántos niños están con usted?',
      options: { 1: '1', 2: '2', 3: '3', 4: '4', '5_plus': '5 o más' },
    },
    applies: {
      label: '¿Alguna de estas aplica a usted?',
      options: {
        veteran: 'Veterano/a',
        dv_survivor: 'Sobreviviente de violencia doméstica',
        disability: 'Tengo una discapacidad',
        physical_health: 'Necesidades de salud física',
        mental_health: 'Necesidades de salud mental',
        substance_use: 'Uso de alcohol o drogas',
        pregnant: 'Embarazada',
        lgbtq: 'LGBTQ+',
        foster_youth: 'Estuve en cuidado de crianza (foster care)',
        recently_released: 'Salí hace poco de la cárcel o prisión',
      },
    },
    work: {
      label: '¿Está trabajando?',
      options: {
        full_time: 'Tiempo completo',
        part_time: 'Medio tiempo',
        day_labor: 'Trabajo por día o trabajitos',
        looking: 'Buscando trabajo',
        unable: 'No puedo trabajar',
        not_looking: 'No estoy trabajando ahora',
      },
    },
    income: {
      label: '¿De dónde viene su dinero?',
      options: {
        job: 'Un trabajo',
        ssi_ssdi: 'SSI o SSDI (discapacidad)',
        va: 'Beneficios de veteranos (VA)',
        snap: 'SNAP (estampillas de comida)',
        tanf: 'TANF (ayuda en efectivo)',
        unemployment: 'Desempleo',
        family_help: 'Ayuda de familia o amigos',
        odd_jobs: 'Trabajitos, reciclaje o pedir ayuda',
        none: 'No tengo ingresos',
        other: 'Otra cosa',
      },
    },
    photo_id: {
      label: '¿Tiene identificación con foto?',
      options: { yes: 'Sí', no: 'No', lost_stolen: 'Tenía, pero se perdió o me la robaron' },
    },
    phone: {
      label: '¿Tiene teléfono?',
      options: { yes_works: 'Sí, y funciona', yes_no_service: 'Sí, pero sin servicio o sin minutos', no: 'No' },
    },
    services_used: {
      label: '¿Qué servicios usa?',
      options: {
        food_pantry: 'Despensa de comida',
        meals: 'Comidas gratis',
        shelter: 'Albergue',
        day_center: 'Centro de día',
        health_clinic: 'Clínica de salud',
        mental_health: 'Atención de salud mental',
        addiction_treatment: 'Tratamiento de drogas o alcohol',
        job_help: 'Ayuda para encontrar trabajo',
        housing_help: 'Ayuda con vivienda',
        id_help: 'Ayuda para sacar identificación',
        showers_laundry: 'Duchas o lavandería',
        transportation: 'Pases de autobús o transporte',
        none: 'Ninguno',
      },
    },
    services_barriers: {
      label: '¿Qué hace difícil usar los servicios?',
      options: {
        hours: 'Los horarios no me funcionan',
        transportation: 'Es difícil llegar',
        rules: 'Las reglas',
        no_pets: 'No aceptan mascotas',
        waitlist: 'Listas de espera',
        no_id: 'Necesito identificación',
        full: 'Están llenos',
        feel_unsafe: 'No me siento seguro/a ahí',
        dont_know_where: 'No sé a dónde ir',
        no_phone: 'Necesito un teléfono',
        other: 'Otra cosa',
      },
    },
    services_missing: {
      label: '¿Qué ayuda falta en Sioux Falls?',
    },
    council_message: {
      label: '¿Qué quiere que sepa el Concejo Municipal?',
    },
  },

  placeholder: {
    title: 'Ayúdenos a traducir esta encuesta',
    body: [
      'Todavía no tenemos esta encuesta en su idioma. Nos encantaría que un vecino nos ayudara a traducirla.',
      'Puede llenar la encuesta en inglés o español ahora. Si puede ayudar a traducir, envíenos una nota abajo.',
    ],
    useEnglish: 'Continue in English',
    useSpanish: 'Continuar en español',
    helpTitle: 'Puedo ayudar a traducir',
    helpName: 'Su nombre (opcional)',
    helpContact: 'Teléfono o correo',
    helpSend: 'Enviar',
    helpSent: '¡Gracias! Nos comunicaremos con usted.',
    helpNeedContact: 'Por favor agregue un teléfono o correo para poder comunicarnos.',
    helpMessage: (languageName) => `Puedo ayudar a traducir la encuesta comunitaria al ${languageName}.`,
  },
};

export default es;
